### ISSUE TITLE
Use getProjects api instead of static data

### ISSUE THREAD

**Issue by kauelima** [kauelima/kauelima.com#2]

**Comment by A-BMT02** [comment]
You need help ?

**Comment by kauelima** [comment]
> You need help ?

I don't think so! Just a designer venturing in nextjs hahah I'm registering issues for my own organization on next steps. But if you have any suggestions they are welcome :)

**Comment by A-BMT02** [comment]
Ah ok , understood 
I'll check it out and see if there's anything i can help with

**Comment by kauelima** [comment]
> Ah ok , understood I'll check it out and see if there's anything i can help with

Thank you! :) I've already build the api route for getProjects and I think i'll need to use react useEffect to change the data source from the current static projects.js to use the data on that api

**Comment by A-BMT02** [comment]
I'll fork it and check it out now

**Comment by A-BMT02** [comment]
Can you please clarify what you mean by "change the data source from the current static projects.js to use the data on that api"

**Comment by kauelima** [comment]
Today, to build my frontpage, I use data from an array i built directly into a file called projects.js. I've already integrated with a third party service (airtable) to have this data outside of my project allowing me to make changes without deploying. The endpoint is at /api/getProjects and working. 

What I need to do now is to use the data on that endpoint on my front page and not the static data on projects.js

I tried importing the function that builds the data on to my imageList component (where I use the data) but for some reason it is giving me an authentication error. All the keys are in my .env file and work well since going to the endpoint URL successfully brings the data. I just need to understand how to pass it to another component.

**Comment by A-BMT02** [comment]
I can see that the data you are using in imageList Component comes from the "Projects" component which is basically a static data 

if i'm getting you correctly , you want the data to be coming from "airtable" ? 
I'm not familiar with airtable , but if thats the issue , i can check them out

**Comment by kauelima** [comment]
> I can see that the data you are using in imageList Component comes from the "Projects" component which is basically a static data
> 
> if i'm getting you correctly , you want the data to be coming from "airtable" ? I'm not familiar with airtable , but if thats the issue , i can check them out

I've already integrated Airtable into the endpoint /api/getProjects but stopped when importing the function of that endpoint did not work as I expected hahah will try more later. But my current issue is, having already built an endpoint with the data I need, how do I use this data on other places on my project. A simple import was not enough.

**Comment by A-BMT02** [comment]
It seems like you imported "projectsData" function from the endpoint to imageList Component 
And it seems like its working fine

**Comment by kauelima** [comment]
Thanks @A-BMT02 after some research on useEffect and fetch I was able to close this issue integrating with an external API
